customCommands:
  - key: "o"
    command: "nvim -c ':Octo pr create'"
    context: "localBranches"
    loadingText: "Loading Octo"
    description: "Open pull request with Octo"
    subprocess: true
keybinding:
  branches:
    createPullRequest: "O"
gui:
  # use the mocha catppuccin theme
  theme:
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - red # Red
